name: Setup Node
description: Setup Node 

inputs:
  install_packages: 
    description: if set `'true'`, install pacages with setup
    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Corepack
      shell: bash
      run: corepack enable

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: Restore `node_modules` caches
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Install dependencies
      if: ${{ inputs.install_packages == 'true' }}
      shell: bash
      run: pnpm install
