name: PR Check

on:
  push:
    branches-ignore:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: ./.github/actions/checkout-setup-node-js
        with:
          install_packages: true

  check:
    needs: setup
    uses: ./.github/workflows/_check.yaml
